services:
  processor:
    build:
      context: ..
      dockerfile: ./processor/Dockerfile
    container_name: processor
    networks:
      - observability
    env_file:
      - .env
    restart: unless-stopped

networks:
  observability:
    external:
      # Point to the actual network name created by the ingest project
      name: ingest_observability