receivers:
  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: monitor_user
    password: monitor_password
    databases:
      - app_db
    collection_interval: 30s
    tls:
      insecure: true
    metrics:
      postgresql.blocks_read:
        enabled: true
      postgresql.commits:
        enabled: true
      postgresql.db_size:
        enabled: true
      postgresql.backends:
        enabled: true
      postgresql.deadlocks:
        enabled: true
      postgresql.rows:
        enabled: true
      postgresql.operations:
        enabled: true

  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      disk:
      network:

processors:
  batch:
    timeout: 10s
    send_batch_size: 100

  resource:
    attributes:
      - key: service.name
        value: otel-collector
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  resourcedetection:
    detectors: [env, system, docker]
    timeout: 5s

exporters:
  kafka:
    brokers:
      - kafka-ingestion:9092
    topic: otel-metrics
    encoding: otlp_proto
    producer:
      compression: gzip
      max_message_bytes: 1000000
    metadata:
      full: true
    timeout: 10s

  logging:
    verbosity: normal
    sampling_initial: 5
    sampling_thereafter: 200

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health
    check_collector_pipeline:
      enabled: true
      interval: 5s
      exporter_failure_threshold: 5

  pprof:
    endpoint: 0.0.0.0:1777

  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    metrics:
      receivers: [postgresql, hostmetrics]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [kafka, logging]

  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888