receivers:
  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: monitor_user
    password: monitor_password
    databases:
      - app_db
    collection_interval: 30s
    tls:
      insecure: true
    metrics:
      postgresql.blocks_read:
        enabled: true
      postgresql.commits:
        enabled: true
      postgresql.db_size:
        enabled: true
      postgresql.backends:
        enabled: true
      postgresql.deadlocks:
        enabled: true
      postgresql.rows:
        enabled: true
      postgresql.operations:
        enabled: true

  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:
      disk:
      network:

  syslog:
    tcp:
      listen_address: "0.0.0.0:5140"
    protocol: rfc3164
    # The 'operators' section with the regex has been removed to allow the default parser to work.

processors:
  batch:
    timeout: 10s
    send_batch_size: 100

  resource:
    attributes:
      - key: service.name
        value: otel-collector
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  resourcedetection:
    detectors: [env, system, docker]
    timeout: 5s

exporters:
  kafka/metrics:
    brokers:
      - kafka-ingestion:9092
    topic: otel-metrics
    encoding: otlp_proto
    producer:
      compression: gzip

  kafka/logs:
    brokers:
      - kafka-ingestion:9092
    topic: raw-host-logs
    encoding: otlp_json

  logging:
    verbosity: normal

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]

  pipelines:
    metrics:
      receivers: [postgresql, hostmetrics]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [kafka/metrics, logging]

    logs:
      receivers: [syslog]
      processors: [memory_limiter, resource, batch]
      exporters: [kafka/logs, logging]

  telemetry:
    logs:
      level: info
