networks:
  proxy:
    name: proxy
    
services:

  setup_config:
    image: hairyhenderson/gomplate:latest
    working_dir: /workspace
    env_file:
      - .env
      - ../.env-local
    volumes:
      - ./templates:/workspace/templates
      - ./generated:/workspace/output
    command: "-f /workspace/templates/hive.properties-template -o /workspace/output/hive.properties \
              -f /workspace/templates/vast.properties-template -o /workspace/output/vast.properties \
              -f /workspace/templates/iceberg.properties-template -o /workspace/output/iceberg.properties"

  traefik:
    image: traefik:v3.1.6
    restart: unless-stopped
    ports:
      - 8443:443
      # - 8080:8080 # dashboard port 
    networks:
      - proxy
    platform: linux/amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # - --api.dashboard=true
      # - --api.insecure=true
      - --log.level=INFO
      - --accesslog=true
      # - --accesslog.format=json
      # - --accesslog.fields.names.ClientUsername=keep
      # - --accesslog.fields.headers.defaultMode=keep
      - --accesslog.fields.names.HealthCheck=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false 
      - --providers.docker.network=proxy
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true

  trino:
    container_name: trino
    image: vastdataorg/trino-vast:${TRINO_VERSION}
    restart: unless-stopped
    depends_on:
      setup_config:
        condition: service_completed_successfully
    mem_limit: 8g
    ports:
      - 18080:8080
    networks:
      - proxy
    platform: linux/amd64
    env_file:
      - path: .env
      - path: ../.env-local
      # The hive image doesn't read the credentials from hdfs-site.xml
      # with inserts or updates.  It expects env vars, so we define them
      # in .env-aws-creds from the S3A_ creds we set in ../.env-local
      - path: ./.env-aws-creds
    volumes:
      - ./generated/vast.properties:/etc/trino/catalog/vast.properties:ro
      - ./generated/hive.properties:/etc/trino/catalog/hive.properties:ro
      - ./generated/iceberg.properties:/etc/trino/catalog/iceberg.properties:ro
      - ./config.properties:/etc/trino/config.properties:ro
    healthcheck:
      # test: ["CMD", "trino", "--execute", "SELECT 'success'"]
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info"]
      interval: 30s
      retries: 10
    labels:
      - traefik.enable=true
      - traefik.http.routers.mytrino.rule=PathPrefix(`/`)
      - traefik.http.routers.mytrino.entrypoints=websecure
      - traefik.http.routers.mytrino.tls=true
      # Define middleware for headers inline.  Ensure ensure trino.properties has ...
      # > http-server.process-forwarded=true
      - traefik.http.routers.mytrino.middlewares=trino-headers@docker
      - traefik.http.middlewares.trino-headers.headers.customRequestHeaders.X-Forwarded-Proto=https
      - traefik.http.services.trino.loadbalancer.healthcheck.path=/v1/info
      - traefik.http.services.trino.loadbalancer.healthcheck.interval=10s
